// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/order.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExchangeType  string                 `protobuf:"bytes,2,opt,name=exchange_type,json=exchangeType,proto3" json:"exchange_type,omitempty"` // "1" 代表沪市, "2" 代表深市
	StockCode     string                 `protobuf:"bytes,3,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // "cre" 或 "del"
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Order) GetExchangeType() string {
	if x != nil {
		return x.ExchangeType
	}
	return ""
}

func (x *Order) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *Order) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_order_proto protoreflect.FileDescriptor

const file_api_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/order.proto\x12\x05model\"\x9e\x01\n" +
	"\x05Order\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rexchange_type\x18\x02 \x01(\tR\fexchangeType\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x03 \x01(\tR\tstockCode\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestampB\x12Z\x10./internal/modelb\x06proto3"

var (
	file_api_proto_order_proto_rawDescOnce sync.Once
	file_api_proto_order_proto_rawDescData []byte
)

func file_api_proto_order_proto_rawDescGZIP() []byte {
	file_api_proto_order_proto_rawDescOnce.Do(func() {
		file_api_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_order_proto_rawDesc), len(file_api_proto_order_proto_rawDesc)))
	})
	return file_api_proto_order_proto_rawDescData
}

var file_api_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_order_proto_goTypes = []any{
	(*Order)(nil), // 0: model.Order
}
var file_api_proto_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_order_proto_init() }
func file_api_proto_order_proto_init() {
	if File_api_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_order_proto_rawDesc), len(file_api_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_order_proto_goTypes,
		DependencyIndexes: file_api_proto_order_proto_depIdxs,
		MessageInfos:      file_api_proto_order_proto_msgTypes,
	}.Build()
	File_api_proto_order_proto = out.File
	file_api_proto_order_proto_goTypes = nil
	file_api_proto_order_proto_depIdxs = nil
}
