// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/q.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order 快照
type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeType  string                 `protobuf:"bytes,1,opt,name=exchange_type,json=exchangeType,proto3" json:"exchange_type,omitempty"`
	StockCode     string                 `protobuf:"bytes,2,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_api_proto_q_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_q_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_q_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfo) GetExchangeType() string {
	if x != nil {
		return x.ExchangeType
	}
	return ""
}

func (x *OrderInfo) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

// Http 查询返回的结构
type QueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Infos         []*OrderInfo           `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResp) Reset() {
	*x = QueryResp{}
	mi := &file_api_proto_q_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResp) ProtoMessage() {}

func (x *QueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_q_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResp.ProtoReflect.Descriptor instead.
func (*QueryResp) Descriptor() ([]byte, []int) {
	return file_api_proto_q_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResp) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *QueryResp) GetInfos() []*OrderInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_api_proto_q_proto protoreflect.FileDescriptor

const file_api_proto_q_proto_rawDesc = "" +
	"\n" +
	"\x11api/proto/q.proto\x12\x05model\"O\n" +
	"\tOrderInfo\x12#\n" +
	"\rexchange_type\x18\x01 \x01(\tR\fexchangeType\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x02 \x01(\tR\tstockCode\"P\n" +
	"\tQueryResp\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12&\n" +
	"\x05infos\x18\x02 \x03(\v2\x10.model.OrderInfoR\x05infosB\x12Z\x10./internal/modelb\x06proto3"

var (
	file_api_proto_q_proto_rawDescOnce sync.Once
	file_api_proto_q_proto_rawDescData []byte
)

func file_api_proto_q_proto_rawDescGZIP() []byte {
	file_api_proto_q_proto_rawDescOnce.Do(func() {
		file_api_proto_q_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_q_proto_rawDesc), len(file_api_proto_q_proto_rawDesc)))
	})
	return file_api_proto_q_proto_rawDescData
}

var file_api_proto_q_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_q_proto_goTypes = []any{
	(*OrderInfo)(nil), // 0: model.OrderInfo
	(*QueryResp)(nil), // 1: model.QueryResp
}
var file_api_proto_q_proto_depIdxs = []int32{
	0, // 0: model.QueryResp.infos:type_name -> model.OrderInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_q_proto_init() }
func file_api_proto_q_proto_init() {
	if File_api_proto_q_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_q_proto_rawDesc), len(file_api_proto_q_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_q_proto_goTypes,
		DependencyIndexes: file_api_proto_q_proto_depIdxs,
		MessageInfos:      file_api_proto_q_proto_msgTypes,
	}.Build()
	File_api_proto_q_proto = out.File
	file_api_proto_q_proto_goTypes = nil
	file_api_proto_q_proto_depIdxs = nil
}
